
LIB=	phoenix

SRCS=	phoenix_iterator.c phoenix_locality.c phoenix_map_reduce.c \
	phoenix_mcs.c phoenix_memory.c phoenix_processor.c phoenix_pt_mutex.c \
	phoenix_scheduler.c phoenix_synch.c phoenix_taskQ.c phoenix_tpool.c

INCFLAGS= -I../dietlibc -I../libpthread -I../dietlibc/cpu/${CPU}

include ../lib.mk
