
LIB=	gomp

SRCS=	gomp_affinity.c gomp_alloc.c gomp_bar.c gomp_barrier.c gomp_critical.c \
	gomp_env.c gomp_error.c gomp_iter.c gomp_iter_ull.c gomp_lock.c \
	gomp_loop.c gomp_loop_ull.c gomp_mutex.c gomp_ordered.c  \
	gomp_parallel.c gomp_proc.c gomp_ptrlock.c gomp_sections.c gomp_sem.c \
	gomp_single.c gomp_task.c gomp_team.c gomp_time.c gomp_work.c

INCFLAGS= -I$(SRCDIR) -I$(SRCDIR)../dietlibc -I$(SRCDIR)../libpthread

include $(SRCDIR)../lib.mk
